### ISSUE TITLE
Products: The product author change to the site author or admin while translation

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan-wpml#10]
**Description of the Bug:**
The product author changes to the site author or admin while translate a product using WPML Classic Editor.

But the product author remains the same if translate a product using WPML Advanced Editor.

**_Video URL:_** http://somup.com/crfhXdbJnZ

**How to produce:**
- Translate a product using WPML Classic Editor.
- The product author change to site author/admin

- Now, try to translate a product using WPML Advanced Editor.
- The product author remains the same.

**Expected Behavior:**
The product author should remain the same if products are translated using WPML Classic Editor.

**System Status:**
Dokan Lite: 3.2.4
Dokan Pro: 3.2.2
Dokan WPML: 1.0.3
WordPress: 5.7
WooCommerce: 5.1.0
WPML Multilingual CMS: 4.4.10

**Comment by strategio** [comment]
This is a bug in WooCommerce Multilingual. I believe it was causing problem only with Dokan.

We'll fix it in WCML 4.12.0.

Here's our internal ticket ((wcml-3611](https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-3611)) for reference.

**Comment by tanjiralmamun** [comment]
Issue Resolved
