### ISSUE TITLE
Dokan Pages: The Dashboard pages and single store doesn't support the Language name added as a parameter setting

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan-wpml#11]
**Description of the Bug:**
If the **_Language URL format_** setting is **_Language name added as a parameter_**, the vendor dashboard pages redirect to the default dashboard menu, and the single store page redirects to the store list page.

**How to reproduce:**
- Choose the **_Language URL format_** setting to **_Language name added as a parameter_** from **_WPML > Languages_** panel
- Now visit the vendor dashboard pages
- It redirects to the default dashboard menu

- Try to visit the single store page
- It redirects to the store list page

**Expected Behavior:**
The vendor dashboard pages and single store should work properly if the **_Language URL format_** setting is **_Language name added as a parameter_**.

**System Status:**
Dokan Lite: 3.2.4
Dokan Pro: 3.2.2
Dokan WPML: 1.0.3
WordPress: 5.7
WooCommerce: 5.1.0
WPML Multilingual CMS: 4.4.10

**Comment by strategio** [comment]
@tanjiralmamun, I believe this should be fixed with https://github.com/weDevsOfficial/dokan/pull/1171.

**Comment by tanjiralmamun** [comment]
Issue Resolved
