### ISSUE TITLE
Account Migration: The "Become a vendor" button redirects to the 404 error page if the account migration WP Endpoint is translated

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan-wpml#13]
**Description of the Bug:**
The **_"Become a vendor"_** button redirects to the 404 error page while visiting from the secondary language if the account migration WP Endpoint is translated.

**_Video URL:_** http://somup.com/crfh2FbJbQ

**How to reproduce:**
- Translate the **_account-migration_** WP Endpoint
- Login as a customer
- Switch to the secondary language
- Click on the **_"Become a vendor"_** button
- It redirects to the 404 error page

**Expected Behavior:**
The **_"Become a vendor"_** button should redirect the correct account migration page from the secondary language if the account migration WP Endpoint is translated.

**System Status:**
Dokan Lite: 3.2.4
Dokan Pro: 3.2.2
Dokan WPML: 1.0.3
WordPress: 5.7
WooCommerce: 5.1.0
WPML Multilingual CMS: 4.4.10

**Comment by strategio** [comment]
@tanjiralmamun, I am suggesting a different approach in the way you are getting dokan subpage links:
- Extend the function `dokan_get_page_url` to accept $subpage as an extra parameter (https://github.com/OnTheGoSystems/dokan/pull/2)
- Improve filter on `dokan_get_page_url` (https://github.com/OnTheGoSystems/dokan-wpml/pull/2)

And inside your plugins (like Dokan PRO), you can replace:

```php
dokan_get_page_url( 'myaccount', 'woocommerce' ) . 'account-migration';
```

with:

```php
dokan_get_page_url( 'myaccount', 'woocommerce', 'account-migration' )
```

I noticed the same problem for several links pointing to `support-tickets` subpage.

=> You will also have to change the callers of `dokan_get_page_url` in the PRO version.

However, `dokan_get_page_url` should be still backward compatible.

**Comment by tanjiralmamun** [comment]
Hi @strategio,

I've informed the development team. They will review your fix and update you soon.

Thank you,

**Comment by tanjiralmamun** [comment]
Issue Resolved
