### ISSUE TITLE
Custom input field texts cannot be translated through WPML

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan-wpml#16]
**Description of the Bug:**
Here is the list of those custom input text fields that cannot be translated through WPML - 

- Setting > General - Vendor Store URL (https://snipboard.io/TpWvUE.jpg),
- Settings > Privacy Policy - Privacy Policy (https://snipboard.io/p2Zegz.jpg),
- Settings > Store Support - Support Button Label (https://snipboard.io/aDUxhE.jpg),
- Settings > Verification SMS Gateways - Verification SMS Gateways - Sender Name, SMS Text, SMS Sent Success, SMS Sent Error (https://snipboard.io/ykroCn.jpg),
- Settings > Email Verification - Registration Notice, Login Notice (https://snipboard.io/cH8ZNM.jpg),
- Settings > Shipping Status - Custom Shipping Status (https://snipboard.io/5icvet.jpg),
- Settings > RMA - Reasons for RMA, Refund Policy (https://snipboard.io/zKFMvh.jpg),
- Settings > Product Report Abuse - Reasons for Abuse Report (https://snipboard.io/Or2fwb.jpg),
- Settings > Single Product MultiVendor - Sell Item Button Text, Available Vendor Display area title (https://snipboard.io/LmzMJk.jpg),
- Settings > Vendor Subscription - Cancelling Email Subject & body, Alert Email Subject & body (https://snipboard.io/gqeurf.jpg)

**How to reproduce:**
Change those fields text to any and search in the WPML > String Translation, those are not available. Only the default texts are available and those don't have any effect even after translated through WPML.

**Expected Behavior:**
Custom input field texts should be translated through WPML.

**System Status:**
Dokan Lite: v3.2.6
Dokan Pro: v3.2.5
Dokan WPML: v1.0.4
WordPress: v5.2.2
WooCommerce: 5.4.1
WPML Multilingual CMS: 4.4.10

**Comment by strategio** [comment]
@tanjiralmamun, for these admin strings, please check this documentation https://wpml.org/documentation/getting-started-guide/string-translation/finding-strings-that-dont-appear-on-the-string-translation-page/#strings-arent-selected-for-translation.

You should be able to select which option fields you want to make translatable. And once you have everything set, you can export the XML configuration and place it at the root of this plugin (as `wpml-config.xml`).

Note that you can add more things to the WPML config, this can be found in https://wpml.org/documentation/support/language-configuration-files/. You can even build the XML file from scratch by the way.

**Comment by tanjiralmamun** [comment]
@strategio Thanks for your response. The solution works correctly.
