### ISSUE TITLE
Product variations in Dokan messed up when added to cart

### ISSUE THREAD

**Issue by smush22** [weDevsOfficial/dokan-wpml#21]
Hello,

I am experiencing an issue:
When a vendor has a product with more than 1 product variation, the cart shows the wrong info
**Here is an example: [This product](https://pleazo.com/product/sexy-pyjama-set-with-lace-2-or-3-piece/) requires the buyer to choose 3 different variations. As you can see in this video, I choose the variations BUT in check out it says the style is "seller’s name" with link to the seller shop (instead the 2-piece style I chose) as seen [here](https://app.usebubbles.com/bTUHCg7NB3h5MWoP2KCt7j/comments-on-pleazo-com).

Dokan says to contact my developer as it looks like it's due to customization, however I do not have a developer and believe it might be due to adding the vendor name to the product pages which also show up in the cart (which I need).

Is there anyway around this to keep the vendor name and have the product variations show up correctly in the cart?

Best,
Chris

**Comment by MdAsifHossainNadim** [comment]
Your problem has been seen and the problem has been checked on the site you provided and my site. No problem is seen here.
Here is the link: https://share.vidyard.com/watch/QFE81wfzGQEjSYrTvdzZLD?
