### ISSUE TITLE
Store Page: The store page redirected to the homepage

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan-wpml#9]
**Description of the Bug:**
The store page redirected to the site homepage while instead of the respective store page while switching to another language.

**How to reproduce:**
- Visit a single store page
- Switch the language
- It redirects to the site homepage.

**Expected Behavior:**
The single store page should not be redirected to the homepage while switching to another language.

**System Status:**
Dokan Lite: 3.2.4
Dokan Pro: 3.2.2
Dokan WPML: 1.0.3
WordPress: 5.7
WooCommerce: 5.1.0
WPML Multilingual CMS: 4.4.10

**Comment by strategio** [comment]
Hi @tanjiralmamun, I am Pierre from WPML compatibility team.

Please check the suggested fix in https://github.com/weDevsOfficial/dokan-wpml/pull/14.

There's probably a better way to get the current store page and I guess you can help (see [my comment](https://github.com/weDevsOfficial/dokan-wpml/pull/14/files#diff-59a282147e5374787852ec69a17423a1d66428e8df2dd216a0c8518bc58f891aR435)).

Could also grant me a developer access on this repository? It will be easier to contribute for both of us.

Thanks!

**Comment by tanjiralmamun** [comment]
Issue Resolved
